### ISSUE TITLE
Release 3.0 to PyPI

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/z3c.evalexception#3]
z3c.evalexception has been ported to Python 3 in git master, but there's no PyPI release with that support.

@philikon is the only person with access to PyPI.  I would be happy to help with the release process if you grant me PyPI access, my username there is **mgedmin**.

**Comment by icemac** [comment]
@philikon Ping. Do you see a chance to share publish rights on PyPI?

**Comment by jugmac00** [comment]
I also pinged him on Twitter.

If there is no reaction, I think you could file an issue at the pypa/pypi tracker.
https://github.com/pypa/pypi-support/issues

**Comment by philikon** [comment]
Hi, sorry folks, I don't check github all that often. I've given both of you access now.

**Comment by icemac** [comment]
@philikon Thank you, I just released https://pypi.org/project/z3c.evalexception/3.0/.
